### ISSUE TITLE
Cant install node red extension

### ISSUE THREAD

**Issue by Schmandre** [csuermann/node-red-contrib-virtual-smart-home#243]
### Bug Description

I am very new to Node RED and unfortunately I cannot get the extension installed. I get the following error message in the log.

Iam using docker with the latest version of node red "image: nodered/node-red:latest"

```
node-red  | 14 Feb 14:18:31 - [info] Installing module: node-red-contrib-virtual-smart-home, version: 4.1.5
node-red  | 14 Feb 14:18:32 - [warn] Installation of module node-red-contrib-virtual-smart-home failed:
node-red  | 14 Feb 14:18:32 - [warn] ------------------------------------------
node-red  | 14 Feb 14:18:32 - [warn] npm WARN config production Use `--omit=dev` instead.
node-red  | npm ERR! code EBADENGINE
node-red  | npm ERR! engine Unsupported engine
node-red  | npm ERR! engine Not compatible with your version of node/npm: fast-unique-numbers@9.0.0
node-red  | npm ERR! notsup Not compatible with your version of node/npm: fast-unique-numbers@9.0.0
node-red  | npm ERR! notsup Required: {"node":">=18.2.0"}
node-red  | npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}
node-red  |
node-red  | npm ERR! A complete log of this run can be found in:
node-red  | npm ERR!     /data/.npm/_logs/2024-02-14T13_18_32_220Z-debug-0.log
node-red  |
```

### To Reproduce

1. Use compose file
2. Try to install extension 

```
version: "3.7"
services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
```

### Expected behavior

Installing extension =)

### Virtual-Smart-Home Version

latest

### Node-RED Version

latest

### Plan

FREE
